### ISSUE TITLE
identity-provider: should redirect to RP with AuthenticationResponse in hash fragment of URL, not query parameters, so that IC Server is never sent the accessToken

### ISSUE THREAD

**Issue by gobengo** [dfinity/agent-js#125]
See 'access token in fragment'

https://tools.ietf.org/html/rfc6749#section-4.2

https://tools.ietf.org/html/rfc6749#section-4.2.2

## Demo

* Use ic-whomi or other authn-integrated site on sodium
* Initiate login
* Finish login, redirecting back to the canister

Expected Behavior:
* the redirect_uri + AuthenticationResponse should NOT have an `?access_token` query string parameter. Instead, it should have a `#access_token=` (and other params) *hash fragment*.
* The `access_token` in the URL is not sent to DFINITY's servers

## Why?

* If the resulting AuthenticationResponse is int he query string of the URL, it will be sent to the server powering `http://{canisterId}.ic0.app`, which isn't really needed (and would allow DFINITY to impersonate the end-user)
* If the resulting AuthenticationResponse is in the fragment component of the URL, it will **not** be sent to the server powering `http://{canisterId}.ic0.app`, which is desirable per https://en.wikipedia.org/wiki/Principle_of_least_privilege

## Implementation Plan

* [x] update `@dfinity/bootstrap` handling of AuthenticationResponseUrlDetectedEvent to appropriately parse authenticationResponse URLs that have the urlencoded AuthenticationResponse in the hash-fragment, not query-string
  * [x] Test that the hash fragment AuthenticationResponse urls work: https://github.com/dfinity/agent-js/pull/232/files#diff-ea0682c3677fd243ab6f9ac79f1d9266a2cd6ebf0d3d159543033c1ad4efde0cR79
* [x] Update ic-id-protocol.md to make explicit that the AuthenticationResponse MUST be in the hash fragment, and remove any language that it's in the query string. (This was always the intention to use the most appropriate oauth2 flow, and implicit flow requires this hash fragment, so want to fix this before wide use)
  * Note: The doc was already pretty explicit about using the hash fragment, so no changes were required.
* [x] agent-js/apps/identity-provider - should createSendResponseUri with AuthenticationResponse hash fragment
