### ISSUE TITLE
[tracking] List of size optimizations for Agent JS

### ISSUE THREAD

**Issue by hansl** [dfinity/agent-js#268]
This is a grocery list of various optimizations to get the size of packages in this repo down.

- [x] Harmony imports #251
- [x] Change package.json according to [this blogpost](https://blog.logrocket.com/publishing-node-modules-typescript-es-modules/)
- [x] Replace Buffers with ArrayBuffer #245
- [ ] Remove CRC32 (which depends on Buffers) #267
- [ ] Remove dependencies from third party libraries #222 
- [x] Replace BigNumber usage with BigInt #269

Other tasks related to size optimization;

- [ ] Add CI step to report size changes in identity-provider #229 
- [x] [Tracking] Separate Candid into its own packages (and move to candid repo) #276
