### ISSUE TITLE
[Tracking] Separate Candid into its own packages (and move to candid repo)

### ISSUE THREAD

**Issue by hansl** [dfinity/agent-js#276]
This would result in the following NPM packages:
- @dfinity/candid
- @dfinity/candid-dom
- @dfinity/principal
- @dfinity/leb

Task list:

- [ ] Get rid of buffer, bignumber and other non desirable dependencies in principal and leb
- [ ] Move principal and leb to own packages
- [ ] Get rid of deps in idl.ts
- [ ] Create @dfinity/candid
- [ ] Move Math.random stuff in @dfinity/candid
- [ ] At some point after this, create @dfinity/candid-dom

**Comment by krpeacock** [comment]
Candid is now its own package, although it still lives in the `agent-js` repo
