### ISSUE TITLE
[Tracking] Launch / Open Source Internal task list

### ISSUE THREAD

**Issue by hansl** [dfinity/agent-js#331]
- [x] Add licenses to all packages
- [x] Move the following apps to their own repo:
  - [x] bootstrap (including worker)
  - [x] identity-provider (including worker, already done?)
- [x] Review dependencies of all packages
- [ ] CI checks for licenses
  - [x] Reach out to @andrew-lee-work to get a list of valid licenses
- [x] Implement #276 
- [x] Implement every issues with the SECREVIEW label:
  - [x] #259
  - [x] #260 
  - [x] #261 
  - [x] #262 
  - [x] #263 
  - [x] #264 
  - [x] #265 
- [x] #266
- [x] #330
- [ ] Nice to have: #247
- [ ] Nice to have: e2e browser tests using cypress and browserstack
  - [ ] Nice to have: move https://github.com/krpeacock/simple-to-do to this repo and use as e2e tests
- [x] Support API v2 (see public spec)
- [x] https://github.com/dfinity/agent-js/issues/347

**Comment by krpeacock** [comment]
Closing since we have open-sourced!
